#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BACKEND_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
ENV_FILE="$BACKEND_DIR/.env"

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate backend/.env" >&2
  exit 1
fi

if [ -f "$ENV_FILE" ] && [ "${FORCE:-}" != "1" ]; then
  echo "$ENV_FILE already exists. Set FORCE=1 to overwrite it." >&2
  exit 1
fi

rand_hex() {
  openssl rand -hex 64
}

JWT_ACCESS_SECRET=$(rand_hex)
JWT_REFRESH_SECRET=$(rand_hex)
LOGIN_CAPTCHA_SECRET=$(rand_hex)
QR_SIGNING_SECRET=$(rand_hex)
DB_PASSWORD=${DB_PASSWORD:-$(rand_hex)}
REDIS_PASSWORD=${REDIS_PASSWORD:-$(rand_hex)}

cat > "$ENV_FILE" <<EOF
# Runtime environment.
NODE_ENV=development
PORT=5000

# PostgreSQL and Redis connection strings.
# Override DB_PASSWORD and REDIS_PASSWORD before running this script if you need fixed local service passwords.
DATABASE_URL=postgresql://trilearn_user:${DB_PASSWORD}@localhost:5432/trilearn
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379

# Generated with openssl rand -hex 64.
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
LOGIN_CAPTCHA_SECRET=${LOGIN_CAPTCHA_SECRET}
QR_SIGNING_SECRET=${QR_SIGNING_SECRET}

FRONTEND_URL=http://localhost:5173
BCRYPT_ROUNDS=12
ACCESS_TOKEN_EXPIRES_IN=15m
REFRESH_TOKEN_EXPIRES_DAYS=7
ALLOW_SOCKET_NO_ORIGIN=false
TRUST_PROXY=
FORCE_HTTPS=false
HEALTHCHECK_KEY=
OPEN_REGISTRATION=false
ATTENDANCE_TIMEZONE=Asia/Kathmandu
TZ=Asia/Kathmandu
QR_SIGNING_SECRET_KEYS=
QR_SIGNING_ACTIVE_KID=
MIN_MOBILE_VERSION=
FCM_SERVER_KEY=
RESEND_SMTP_HOST=smtp.resend.com
RESEND_SMTP_PORT=587
RESEND_SMTP_USER=resend
RESEND_SMTP_PASS=
RESEND_SMTP_SECURE=false
RESEND_API_KEY=
MAIL_FROM=TriLearn <no-reply@yourdomain.com>
ENABLE_PASSWORD_RESET=false
DEBUG_ERRORS=false
ENABLE_API_DOCS=false
DISABLE_RATE_LIMITS=false
LOGIN_RATE_LIMIT_MAX=10
LOGIN_RATE_LIMIT_WINDOW_MS=900000
REFRESH_TOKEN_CLEANUP_INTERVAL_MS=21600000
ATTENDANCE_SYNC_INTERVAL_MS=300000
AUDIT_LOG_CLEANUP_INTERVAL_MS=86400000
NOTIFICATION_WORKER_CONCURRENCY=2
AUDIT_LOG_RETENTION_DAYS=180
MAX_PDF_UPLOAD_BYTES_ADMIN=15728640
MAX_PDF_UPLOAD_BYTES_COORDINATOR=15728640
MAX_PDF_UPLOAD_BYTES_INSTRUCTOR=15728640
MAX_PDF_UPLOAD_BYTES_STUDENT=10485760
SOCKET_EVENT_RATE_LIMIT_MAX=60
SOCKET_EVENT_RATE_LIMIT_WINDOW_MS=10000
PGPOOL_MAX=10
PGPOOL_MIN=0
PGPOOL_IDLE_TIMEOUT_MS=10000
PGPOOL_CONNECTION_TIMEOUT_MS=10000
PGPOOL_MAX_USES=0
PGSSL_REJECT_UNAUTHORIZED=false
UPLOAD_DIR=uploads
UPLOAD_PUBLIC_PATH=/api/v1/uploads
UPLOAD_BASE_URL=
S3_BUCKET=
S3_REGION=
S3_ACCESS_KEY=
S3_SECRET_KEY=
S3_ENDPOINT=
S3_FORCE_PATH_STYLE=false
S3_PRESIGNED_URL_TTL_SECONDS=300
TEST_DATABASE_URL=
# DEFAULT_STUDENT_PASSWORD has been removed. A unique random password is generated for each new student account.
EOF

chmod 600 "$ENV_FILE"
echo "Generated $ENV_FILE"
